{% set name = "llvmlite" %}
{% set version = "0.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llvmlite-{{ version }}.tar.gz
  sha256: 227c9fd6d09dce2783c18b754b7cd9d9b3b3515210c46acc2d3c5badd9870ceb
  patches:  # [win]
    - patches/0001-use-conda-env.patch  # [win]

build:
  number: 0
  skip: true  # [py<310]
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                   # [unix]
    - ninja-base             # [win]
  host:
    - python
    - pip
    - setuptools
    # Statically linking to llvmdev ! see comments in build.sh
    - llvmdev 20.*
    # zlib on win because our llvmdev is not built with LLVM_ENABLE_ZLIB=OFF
    # zlib and zstd on others because we are statically linking to llvmdev
    - zlib {{ zlib }}
    - zstd {{ zstd }}
  run:
    - python
    - zlib # bounds through run_exports
    - zstd # bounds through run_exports

test:
  requires:
    - pip
    - py-lief
  imports:
    - llvmlite
    - llvmlite.binding
    - llvmlite.ir
    - llvmlite.tests
  commands:
    - pip check
    - export LLVMLITE_DIST_TEST='1'  # [unix]
    - set LLVMLITE_DIST_TEST="1"     # [win]
    - python -m llvmlite.tests
  downstreams:
    - numba

about:
  home: https://llvmlite.readthedocs.io
  license: BSD-2-Clause AND Apache-2.0 WITH LLVM-exception
  license_file:
    - LICENSE
    - LICENSE.thirdparty
  summary: A lightweight LLVM python binding for writing JIT compilers.
  description: |
    llvmlite provides a Python binding to LLVM for use in Numba. Numba previously relied on llvmpy.
  doc_url: https://llvmlite.pydata.org
  dev_url: https://github.com/numba/llvmlite

extra:
  skip-lints:
    # llvmlite is a LLVM python binding, which is why it uses llvm directly in host
    - should_use_compilers
  recipe-maintainers:
    - jakirkham
    - souravsingh
    - marcelotrevisani
    - xhochy
    - mbargull
