{% set name = "llvmlite" %}
{% set version = "0.23.1" %}
{% set build_number = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/numba/llvmlite
  git_rev: v{{ version }}
  # Wait for py37 to release or for next llvmlite version
  patches:
    - 0001-Python-3.7-compat-Properly-escape-repl-in-re.sub.patch

build:
  number: {{ build_number }}
  script_env:
    - PY_VCRUNTIME_REDIST

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
  host:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 6.0*
    - vs2015_runtime # [win]
    # The DLL build uses cmake on Windows
    - cmake          # [win]
    - enum34         # [py27]
    # llvmdev is built with libz compression support
    - zlib           # [unix]
  run:
    - python
    - enum34         # [py27]
    - vs2015_runtime # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1 # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
