{% set name = "llvmlite" %}
{% set version = "0.23.0" %}
{% set sha256 = "bc8b1b46274d05b578fe9e980a6d98fa71c8727f6f9ed31d4d8468dce7aa5762" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Python-3.7-compat-Properly-escape-repl-in-re.sub.patch
    
build:
  number: 0
  script_env:
    - PY_VCRUNTIME_REDIST
  ignore_run_exports:
    # Is static-linked
    - xar

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 6.0*
    - vs2015_runtime [win]
    # The DLL build uses cmake on Windows
    - cmake          [win]
    - enum34         [py27]
    - zlib
    - xar # [osx]
  run:
    - python
    - enum34         [py27]
    - vs2015_runtime [win]
    - zlib

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
