{% set name = "llvmlite" %}
{% set version = "0.27.1" %}
{% set sha256 = "ef222a5b14d883fe7cc7ff23a03c2c2d2f3312f3505eed71cf9d4feea6adf16d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/numba/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script_env:
    - PY_VCRUNTIME_REDIST
  skip: true  # [win and py==27]

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [linux or (win and py==27)]
    - {{ compiler('cxx') }}  # [linux or (win and py==27)]
    - vs2017_win-64          # [win64 and py>27]
    - vs2017_win-32          # [win32 and py>27]
    # The DLL build uses cmake on Windows
    - cmake                  # [win]
    - make                   # [unix]
  host:
    - python
    - llvmdev 7.0.*
    - enum34          # [py27]
    # llvmdev is built with libz compression support
    - zlib            # [unix]
  run:
    - python
    - enum34          # [py27]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1  # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: http://llvmlite.pydata.org
  license: BSD-2-clause
  license_file: LICENSE
  summary: A lightweight LLVM python binding for writing JIT compilers.
  doc_url: http://llvmlite.pydata.org/
  dev_url: https://github.com/numba/llvmlite

extra:
  recipe-maintainers:
    - souravsingh
