travis:
  secure:
    BINSTAR_TOKEN: x4YFW0Xs6fgBv4KXFilvrXxBOUF6mhx6cirwi/xcJXhjf+buHWydORltmfzz4IFfggsLFJYlUN5xWQCHA9s+FC1lxasTfrl/tnne8fbjIkuOCroZFpX2Jgnoc8zI5I9L/Q/m36mbXtWzSJ9liyWH/RrgqvCoEiPqfR+3+cOqr3vHaxxSTODxhdLgyjP+2Wi9KFzavWfiSuC7+8dmO70uYs+FvrevHwzhTcBUTdoP1ueA2NFp14rKloURawmzseRaPMdLrCYq4j+DygLNXWg9gwQKIDQM9CcTEf13pAqbM8RNotcE+guqtcz7+sGtVHP4znkPTK5t6yRH7zfIrqawQbnqhBOQCNfKUf6gk9qWKnHDcbUunOTj/lAV97Rqwj9RiDLptiUrO+UPA/2il/gn5L1pdQJtUNbh5WiU3JxwosGrW5ZXg11KbDLNj+2+V3Gus+3AQJyUP/frPFV0G0tJVmTC4QnPSf54gi1cCmMr+HyEFdonQJVvbgliRDKjraXVYfIowYAPEmi6LpB8/5Vv7QEG9e7pDKwK0BHF2ST0l1U4hRz2oaF0XOy4ixddMbJ6/Qeadi45gmBjNzWuxHO4OQ4aUotco6jLVQhy6PM9oz5KAtRPB3eQAp7HiN21x3dv7rcakv+b6SD/PJNi9MVoafLaME652xrGAzlACwFshRA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
